org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.219

## Mod Properties
mod_id=crystal_clear
mod_name=Create: Crystal Clear
mod_license=All Rights Reserved
mod_version=2.0-Beta
mod_group_id=com.cyvack
mod_authors=Cyvack
mod_description=Compatible with Create 6+\nThe Ultimate Glass Experience.

# Create Dependencies
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
